version: "3.8"

services:
  www:
    image: arm64v8/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
